### ISSUE TITLE
v10 support?

### ISSUE THREAD

**Issue by Cempres** [fantasycalendar/FoundryVTT-TokenEase#14]
Hopefully we'll get it, as this is an amazing tool in our games!

**Comment by Cempres** [comment]
@Haxxer any updates on this perchance?

**Comment by Haxxer** [comment]
None yet. The module is open source, so if you wish to have it in v10, you can always updated the module and open a pull request :)

**Comment by Cempres** [comment]
> None yet. The module is open source, so if you wish to have it in v10, you can always updated the module and open a pull request :)

I would love to If I had any proper knowledge of coding! :) I'll keep quiet and hope someone more capable would be able to do it!

**Comment by Haxxer** [comment]
Added in 1.2.0
