### ISSUE TITLE
Token Movement Duration doesn't work

### ISSUE THREAD

**Issue by neutromancer** [fantasycalendar/FoundryVTT-TokenEase#18]
If I set Duration to anything other than 0, it disables the animation altogether, except for when you drag exactly one grid space away.
Doesn't matter if I set it to 1, 10, or 60 seconds, it just moves the token instantaneously. And when you drag it one grid space, it uses the Speed setting anyway.

**Comment by roguedevjake** [comment]
> If I set Duration to anything other than 0, it disables the animation altogether, except for when you drag exactly one grid space away. Doesn't matter if I set it to 1, 10, or 60 seconds, it just moves the token instantaneously. And when you drag it one grid space, it uses the Speed setting anyway.

I know this is an old issue, but are you sure you haven't mistaken milliseconds for seconds. e.g. a 60 in the field will mean 0.06 of a second

**Comment by Haxxer** [comment]
![image](https://user-images.githubusercontent.com/12858387/212554287-5806d3e0-675f-4262-8242-c709745cb99e.png)

**Comment by neutromancer** [comment]
> > If I set Duration to anything other than 0, it disables the animation altogether, except for when you drag exactly one grid space away. Doesn't matter if I set it to 1, 10, or 60 seconds, it just moves the token instantaneously. And when you drag it one grid space, it uses the Speed setting anyway.
> 
> I know this is an old issue, but are you sure you haven't mistaken milliseconds for seconds. e.g. a 60 in the field will mean 0.06 of a second

Thank you, I had indeed mistaken the field for seconds.
