### ISSUE TITLE
v11 compatibility

### ISSUE THREAD

**Issue by Spappz** [fantasycalendar/FoundryVTT-TokenEase#19]
I've been using this for a few weeks on v11 with no problems anywhere, so probably doesn't need an update beyond `module.json`.

**Comment by Intervencion** [comment]
@Haxxer Apologies for the ping, but bump-
Can't see any problem with the module on 11.315 either

**Comment by weepingminotaur** [comment]
Also echoing the request to bump formal compatibility to v11 (even though it already works fine in v11). I want the compatibility warning for it to turn off. :)

**Comment by Spappz** [comment]
Resolved by ea6bd85
