### ISSUE TITLE
V9T2, Mod conflict with new libRuler based Drag Ruler and Pathfinding Ruler for v9

### ISSUE THREAD

**Issue by apoapostolov** [fantasycalendar/FoundryVTT-TokenEase#3]
I am testing it on v9T2 along with other mods and I found that the mod has conflict with caewok's new libRuler-based Drag Ruler and Pathfinding Ruler, both being adopted by him for v9. The conflict is that while DR and PR work as intended, Token Ease causes the token to move straight from point A to point Z ignoring any segments B,C, D etc. despite being visualized.

Pathfinding Ruler - https://github.com/caewok/foundry-vtt-pathfinding-ruler
Drag Ruler - https://github.com/caewok/foundryvtt-drag-ruler

**Comment by caewok** [comment]
Looks to me like the 1.0.4 release fixes this issue, which is related to https://gitlab.com/foundrynet/foundryvtt/-/issues/5928. @apoapostolov can confirm if it works for him.

**Comment by Haxxer** [comment]
Fixed in 1.0.4
