### ISSUE TITLE
Feature Request: Drag Ruler compatibility

### ISSUE THREAD

**Issue by GambetTV** [fantasycalendar/FoundryVTT-TokenEase#4]
Drag Ruler is a very popular module, but unfortunately there's what I would consider to be a bit of an incompatibility between it and your module. They work together well enough, but Drag Ruler allows you to create waypoints for your token, so you might drag your token 10 feet, then right click to set a waypoint, and drag it to the left 20 more feet. When you let go the token will follow the path.

Unfortunately with your module, Token Movement Duration winds up applying *per* waypoint. So if I set it to 1000 (1 second) and drag my token 30 feet and let go, it will go 30 feet in 1 second. But if  I drag 10 feet, make a waypoint, drag 10 more feet, make a waypoint, drag 10 more feet, then let go, even though I'm going the same 30 foot distance in one turn, it will now take me 3 seconds to go the same distance.

This might be outside the scope of the module, but if you could allow it to take into account the total distance moved rather than each waypoint that would be extremely cool.

**Comment by Haxxer** [comment]
It certainly is a tough one as Drag Ruler treats each part of the waypoints as discrete movements, meaning to Token Ease, it is as if someone dragged it from point A to B, then B to C, then C to D.

I'll file this under "nice to haves", but no guarantees.

**Comment by Haxxer** [comment]
Closing as won't do
