### ISSUE TITLE
Feature Request: modifier key to diable animations

### ISSUE THREAD

**Issue by paulohdsc** [fantasycalendar/FoundryVTT-TokenEase#6]
First of all, thanks for the module!

Would it be possible to implement an option so that GMs can set a modifier key to disable token animations? This would be especially useful when the GM wants to move a token without revealing fog of war.

**Comment by Haxxer** [comment]
Added in 1.0.5

**Comment by Ikabodo** [comment]
I don't know if this is the intention, but the animation is still played for the players. 
This sort of defeats the purpose of OP:s request. Since the player will still get fog of war revealed if the GM holds the modifing key.

**Comment by Haxxer** [comment]
Fixed again in 1.1.0
