### ISSUE TITLE
Feature Request: allow users to set Token Ease configurations in a per token basis

### ISSUE THREAD

**Issue by paulohdsc** [fantasycalendar/FoundryVTT-TokenEase#7]
Are there any plans to allow users to set Token Ease configurations in a per token basis, via Token Configuration Window or API? I believe it would be a great addition to your module.

I know it's possible to use the API to customize changes to Token.Document.Update, but it would be nice if it was possible to set "per token" easing defaults.

**Comment by Haxxer** [comment]
Added in 1.1.0
