### ISSUE TITLE
When used in conjunction with MATT, Token Ease doesn't respect the expected "teleportation" behavior when using MATT's `Teleport Token from Point A to B` action. It eases the token instead.

### ISSUE THREAD

**Issue by PlasticMohawk** [fantasycalendar/FoundryVTT-TokenEase#8]
![image](https://user-images.githubusercontent.com/5216225/152807335-e84aea28-af57-401b-ba3f-76191ce1629b.png)

Using these settings, if `Token Ease` is enabled, the token will ease to the new location over time, instead of disappearing and reappearing at the destination as is expected with "teleport" style movement. With `Token Ease` disabled, the token teleports as expected.

**Comment by Haxxer** [comment]
Fixed in 1.1.0
